insert into personajes (id , nombre) values (01, 'Mario');
insert into personajes (id , nombre) values (02, 'Donkey-Kun');
insert into personajes (id , nombre) values (03, 'Link');
insert into personajes (id , nombre) values (04, 'Samus');
insert into personajes (id , nombre) values (05, 'Samus Oscura');
insert into personajes (id , nombre) values (06, 'Yoshi');
insert into personajes (id , nombre) values (07, 'Kirby');
insert into personajes (id , nombre) values (08, 'Fox');
insert into personajes (id , nombre) values (09, 'Pikachu');
insert into personajes (id , nombre) values (10, 'Luigi');
insert into personajes (id , nombre) values (11, 'Ness');   
insert into personajes (id , nombre) values (12, 'Captain Falcon');
insert into personajes (id , nombre) values (13, 'Jigglypuff');
insert into personajes (id , nombre) values (14, 'Peach');
insert into personajes (id , nombre) values (15, 'Daisy');
insert into personajes (id , nombre) values (16, 'Bowser');
insert into personajes (id , nombre) values (17, 'Bowsette');
insert into personajes (id , nombre) values (18, 'Dr. Mario');
insert into personajes (id , nombre) values (19, 'Pichu');
insert into personajes (id , nombre) values (20, 'Zelda');
insert into personajes (id , nombre) values (21, 'Ice Climbers');
insert into personajes (id , nombre) values (22, 'Sheik');
insert into personajes (id , nombre) values (23, 'Falco');
insert into personajes (id , nombre) values (24, 'Marth');
insert into personajes (id , nombre) values (25, 'Lucina');
insert into personajes (id , nombre) values (26, 'Link niño');
insert into personajes (id , nombre) values (27, 'Ganondorf');
insert into personajes (id , nombre) values (28, 'Dr. Ganondorf');
insert into personajes (id , nombre) values (29, 'Mewtwo');
insert into personajes (id , nombre) values (30, 'Roy');
insert into personajes (id , nombre) values (31, 'Chrome');
insert into personajes (id , nombre) values (32, 'Mr. Game & Watch');
insert into personajes (id , nombre) values (33, 'Meta Knight');
insert into personajes (id , nombre) values (34, 'Pit');
insert into personajes (id , nombre) values (35, 'Pit Sombrío');
insert into personajes (id , nombre) values (36, 'Dr. Pit Sombrío');
insert into personajes (id , nombre) values (37, 'Samus Zero');
insert into personajes (id , nombre) values (38, 'Wario');
insert into personajes (id , nombre) values (39, 'Snake');
insert into personajes (id , nombre) values (40, 'Ike');
insert into personajes (id , nombre) values (41, 'Young Ike');
insert into personajes (id , nombre) values (42, 'Dr. Ike');
insert into personajes (id , nombre) values (43, 'Entrenador Pokemon');
insert into personajes (id , nombre) values (44, 'Diddy-kun');
insert into personajes (id , nombre) values (45, 'Lucas');
insert into personajes (id , nombre) values (46, 'Sonic');
insert into personajes (id , nombre) values (47, 'Rey Dedede');
insert into personajes (id , nombre) values (48, 'Olimar');
insert into personajes (id , nombre) values (49, 'Lucario');
insert into personajes (id , nombre) values (50, 'R.O.B.');
insert into personajes (id , nombre) values (51, 'Toon Link');
insert into personajes (id , nombre) values (52, 'Wolf');
insert into personajes (id , nombre) values (53, 'Murabito');
insert into personajes (id , nombre) values (54, 'Mega Hombre');
insert into personajes (id , nombre) values (55, 'Entrenadora de Wii Fit');
insert into personajes (id , nombre) values (56, 'Estela y Destello');
insert into personajes (id , nombre) values (57, 'Pequeño Mac');
insert into personajes (id , nombre) values (58, 'Greninja');
insert into personajes (id , nombre) values (59, 'Mii Karateka');
insert into personajes (id , nombre) values (60, 'Mii Espadachín');
insert into personajes (id , nombre) values (61, 'Keanu Reeves');
insert into personajes (id , nombre) values (62, 'Palutena');
insert into personajes (id , nombre) values (63, 'Pac-Man');
insert into personajes (id , nombre) values (64, 'Daraen');
insert into personajes (id , nombre) values (65, 'Shulk');
insert into personajes (id , nombre) values (66, 'Bowsy');
insert into personajes (id , nombre) values (67, 'Dúo Duck Hunt');
insert into personajes (id , nombre) values (68, 'Ryu');
insert into personajes (id , nombre) values (69, 'Cooler Ryu');
insert into personajes (id , nombre) values (70, 'Dr. Ryu');
insert into personajes (id , nombre) values (71, 'Nube');
insert into personajes (id , nombre) values (72, 'Corrin');
insert into personajes (id , nombre) values (73, 'Bayonetta');
insert into personajes (id , nombre) values (74, 'Inkling');
insert into personajes (id , nombre) values (75, 'Ridley');
insert into personajes (id , nombre) values (76, 'Simon');
insert into personajes (id , nombre) values (77, 'Cooler Simon');
insert into personajes (id , nombre) values (78, 'Rey K. Rool');
insert into personajes (id , nombre) values (79, 'Canelita');
insert into personajes (id , nombre) values (80, 'Incineroar');
insert into personajes (id , nombre) values (81, 'Planta Piraña');
insert into personajes (id , nombre) values (82, 'Señor Sarcasmo');
insert into personajes (id , nombre) values (83, 'Heroe');
insert into personajes (id , nombre) values (84, 'Waluigi');
insert into personajes (id , nombre) values (85, 'Sans');
insert into personajes (id , nombre) values (86, 'Dr. Sans');
insert into personajes (id , nombre) values (87, 'Banjo & Kazooie');




insert into mapas(id,nombre) values (1,'Campo de batalla') ;
insert into mapas(id,nombre) values (2,'Destino Final ') ;
insert into mapas(id,nombre) values (3,'Yoshis Story') ;
insert into mapas(id,nombre) values (4,'Isla de Yoshi ') ;
insert into mapas(id,nombre) values (5,'Sistema Lylat') ;
insert into mapas(id,nombre) values (6,'Estadio Pokemon 2') ;
insert into mapas(id,nombre) values (7,'Castillo Asediado') ;
insert into mapas(id,nombre) values (8,'Pueblo Smash') ;
insert into mapas(id,nombre) values (9,'Teselia') ;
insert into mapas(id,nombre) values (10,'Kalos') ;
insert into mapas(id,nombre) values (11,'Sobrevolando el pueblo') ;
insert into mapas(id,nombre) values (12,'Wario Ware') ;
insert into mapas(id,nombre) values (13,'Mementos') ;
insert into mapas(id,nombre) values (14,'Final Completo') ;